environments:
  development:
    secrets:
      - environments/development/secrets.yaml

---

repositories:
  - name: hashicorp
    url: https://helm.releases.hashicorp.com 
  - name: stakater 
    url: https://stakater.github.io/stakater-charts 

helmDefaults:
  atomic: false
  cascade: background
  cleanupOnFail: false
  createNamespace: true
  devel: false
  force: false
  historyMax: 10
  kubeContext: vin
  recreatePods: false
  skipDeps: false
  timeout: 30 
  # timeout: 300
  wait: true
  waitForJobs: false  

releases:
  - name: vault
    chart: hashicorp/vault
    version: 0.29.1
    namespace: vault
    labels:
      tier: core
    values:
      - environments/{{ .Environment.Name}}/vault.yaml

  - name: vault-operator
    chart: hashicorp/vault-secrets-operator
    version: 0.9.1
    namespace: vault
    labels:
      tier: core
    values:
      - environments/{{ .Environment.Name}}/vault-operator.yaml
    needs:
      - vault/vault

  - name: reloader
    installed: false
    chart:  stakater/reloader
    namespace: core
    labels:
      tier: core

  - name: devops
    chart: ./charts/devops
    namespace: core
    labels:
      tier: core
      instance: devops
    values:
      - db:
          password: {{ .Values.db.password }}

  - name: app1-back
    chart: ./charts/backend
    namespace: backend
    labels:
      tier: backend
      instance: app1
    needs: 
      - vault/vault-operator
      - core/devops
    values:
      - name: app1-back

  - name: app1-front
    chart: ./charts/frontend
    namespace: frontend
    labels:
      tier: frontend
      instance: app1
    needs:
      - backend/app1-back
    values:
      - name: app1-front
    

  - name: backend
    chart: ./charts/backend
    namespace: default
    labels:
      tier: backend
      type: app
    needs: 
      - vault/vault
      - core/devops

  - name: frontend
    chart: ./charts/frontend
    namespace: default
    labels:
      tier: frontend
      type: app
    needs:
      - backend

