apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "frontend.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend: 
              service:
                name: {{ include "frontend.name" . }}
                port: 
                  number: 80

