apiVersion: v1
kind: Secret
metadata: 
  name: app2-back-database
  namespace: backend
type: Opaque
data:
  DB_HOST: {{ b64enc .Values.db.host }}
  DB_USER: {{ b64enc .Values.db.user }}
  DB_PASSWORD: {{ b64enc .Values.db.password }}

  
