apiVersion: v1
kind: Secret
metadata: 
  name: database
  namespace: default
type: Opaque
data:
  DB_HOST: {{ b64enc .Values.db.host }}
  DB_USER: {{ b64enc .Values.db.user }}
  SOPS_DB_PASSWORD: {{ b64enc .Values.db.password }}

  
