{{- range .Values.namespaces }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-all
  namespace: {{ . }}
spec:
  podSelector: {}
  policyTypes:
    # - Egress
    - Ingress
---
{{- end}}
