apiVersion: v1
kind: LimitRange
metadata:
  name: backend-limits
  namespace: frontend
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 100m
        memory: 100Mi
      max:
        cpu: 500m
        memory: 500Mi
