# apiVersion: networking.k8s.io/v1
# kind: NetworkPolicy
# metadata:
#   name: {{ include "backend.name" . }}
#   namespace: {{ .Release.Namespace }}
# spec:
#   podSelector:
#     matchLabels:
#       app.kubernetes.io/instance: {{ include "backend.name" . }}
#   policyTypes:
#   - Ingress
#   ingress:
#   - from:
#     - namespaceSelector:
#         matchLabels:
#           kubernetes.io/metadata.name: frontend
#       podSelector:
#           matchLabels:
#             app.kubernetes.io/instance: {{ .Values.name }}-front
#     - podSelector:
#           matchLabels:
#             app.kubernetes.io/instance: {{ include "backend.name" . }}
#
