{{- if eq .Values.secrets.managedBy "vault" }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: static-auth
  namespace: backend
spec:
  method: kubernetes
  mount: vis
  kubernetes:
    role: {{ .Values.name }}
    serviceAccount: {{ include "backend.serviceAccountName" . }}
    audiences:
      - vault
{{- end }}
